### ISSUE TITLE
(Request) Reinstate  YTSpeed options

### ISSUE THREAD

**Issue by Usagyuuuun** [Balackburn/YTLitePlus#10]
Would it be possible to reinstate YTSpeed options that has just been removed from YTLitePlus. Reason being is that YTSpeed has the additional speed settings of 3.25 and 3.75x which I use quite frequently.

Thank you to all the devs for this wonderful app. Keep up the good work!

**Comment by Balackburn** [comment]
Hello it was removed because it was duplicate with YTLite "Extra speed options" but after checking it doesn’t add x3.25 and x3.75 only x3 & x3.5 I will add it back just for you, you can ask the YTLite dev for more speed options maybe he will add them so it won’t need to be duplicates options.

**Comment by Balackburn** [comment]
@arichorn Thx 🙏 you aren’t an idiot

**Comment by Balackburn** [comment]
@Usagyuuuun fixed in last release

**Comment by Usagyuuuun** [comment]
Thank you @Balackburn and @arichorn for indulging me on this weird request! This IPA is just a pleasure to use!

**Comment by GH05Tin** [comment]
I don’t know if I have to open a new request for this, will gladly do if needed but here goes since it’s related: Is it possible to implement the custom speed like on desktop YT somehow? Would be awesome if there was option to change the long-press speed with this custom option (i.e. 1.05x or 1.15x and so on, I find I use these kind of speeds a lot watching/listening podcasts)

Thanks for the awesome work on this project guys! Best regards.

**Comment by GH05Tin** [comment]
Awesome, thank you very much for everything you do for us ad-haters and better-app lovers!
