### ISSUE TITLE
Video won't restart from where I left off after I close it. 

### ISSUE THREAD

**Issue by leryeo** [Balackburn/YTLitePlus#94]
There are often cases where the video won't restart from where you left off. Sometimes after reloading the video it only updates the progress bar so it's 30 minutes behind where I was in the video. Sometimes it doesn't even remember my progress and plays from the beginning. 

Is there something in the settings of YouTube or YTLitePlus I ought to be changing or enabling to fix this?

**Comment by Balackburn** [comment]
Hello did you enabled Youtube history? Otherwise you didn't followed the issue template and the instructions! 

I think your issue isn't with YTLitePlus but with Youtube, so please don't open an issue here for that and read the instruction. You can test with the normal version of Youtube to see if it's from the tweaks or not.
